version: "3"

services:
 redis:
    image: "redis:alpine"
    command: /bin/sh -c "redis-server --requirepass $$REDIS_PASSWORD"
    environment:
      REDIS_PASSWORD: password
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
